# https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
  publish = "public"

[context.deploy-preview]
  command = "gatsby build"
  ignore = "git diff --quiet HEAD^ HEAD || git log -1 --pretty=%an | xargs | grep -q dependabot-preview"

  [context.deploy-preview.environment]
    NODE_VERSION = "12.14.0"
    RUBY_VERSION = "2.6.2"


[context.branch-deploy]
  command = "gatsby build"
  ignore = "git diff --quiet HEAD^ HEAD || git log -1 --pretty=%an | xargs | grep -q dependabot-preview"

  [context.branch-deploy.environment]
    NODE_VERSION = "12.14.0"
    RUBY_VERSION = "2.6.2"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "netlify-plugin-a11y"

  [plugins.inputs]
  resultMode = "warn"
  checkPaths = ['/']
