backend:
  name: github
  branch: v2-master
  site_domain: dds.mil
  repo: deptofdefense/dds.mil

site_url: https://dds.mil/
display_url: DDS.mil
logo_url: /img/logo-cms.png
publish_mode: editorial_workflow
media_folder: content/media
public_folder: ""

collections:
  - name: "announcements"
    label: "Announcements"
    label_singular: "Announcement"
    description: >
      General annoucements from the DDS team.
    folder: "content/announcements"
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: "/announcements/{{slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "type",
          name: "Type",
          widget: "hidden",
          default: "announcement",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          tagname: "",
          hint: "Determines order of announcements page",
        }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          required: false,
        }
      - { label: "Summary", name: "summary", widget: "string", tagname: "" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Blog Posts"
    label_singular: "Blog Post"
    description: >
      Blog Posts from the DDS team.
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: "/blog/p/{{slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "type", name: "Type", widget: "hidden", default: "post" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          tagname: "",
          hint: "Determines order of announcements page",
        }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          required: false,
        }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          required: false,
          valueField: "slug",
          collection: "team",
          searchFields: "name",
          optionsLength: 5,
        }
      - { label: "Summary", name: "summary", widget: "string", tagname: "" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "team"
    label: "Team Members"
    label_singular: "Team Member"
    description: >
      DDS Team members.
    folder: "content/team"
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: "/team"
    summary: "{{name}}"
    identifier_field: "name"
    create: true
    editor:
      preview: true
    fields:
      - { label: "type", name: "Type", widget: "hidden", default: "teamMember" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Joined", name: "joined", widget: "datetime", tagname: "" }
      - { label: "Bio", name: "bio", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image", required: false }

  - name: "news"
    label: "DDS in the News"
    label_singular: "News Article"
    description: >
      References to articles posted about DDS.
    folder: "content/news"
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: "/news"
    summary: "{{year}}/{{month}} | {{title}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "type",
          name: "Type",
          widget: "hidden",
          default: "newsArticle",
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "External Link", name: "link", widget: "string" }

  - name: "pages"
    label: "Content Pages"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "homePage"
        file: "content/pages/homePage.json"
        fields:
          - label: "Hero Section"
            name: "heroSection"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Hero Image",
                  name: "img",
                  widget: "image",
                  hint: "image should be high resolution with an aspect ratio appropriate for the hero image",
                }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "CTA", name: "cta", widget: "string" }
              - { label: "CTA Link", name: "ctaLink", widget: "string" }
          - label: "Text Info Section"
            name: "textSection"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Main Text",
                  name: "mdMain",
                  widget: "markdown",
                  hint: "this field supports markdown, but should stick to simple things like bold, italic, etc.",
                }
              - {
                  label: "Call Out",
                  name: "mdCallout",
                  widget: "markdown",
                  hint: "this field supports markdown, but should stick to simple things like bold, italic, etc.",
                }
          - label: "Icon Section"
            name: "iconSection"
            widget: "list"
            fields:
              - { label: "heading", widget: "string", name: "heading" }
              - { label: "Details", widget: "string", name: "details" }
              - {
                  label: "icon",
                  widget: "image",
                  name: "icon",
                  hint: "SVG format",
                }
              - { label: "CTA", widget: "string", name: "cta", required: false }
              - {
                  label: "CTA Link",
                  widget: "string",
                  name: "ctaLink",
                  required: false,
                }
          - label: "CTA Section"
            name: "ctaSection"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Details",
                  name: "mdDetails",
                  widget: "markdown",
                  hint: "this field supports markdown, but should stick to simple things like bold, italic, etc.",
                }
              - {
                  label: "CTA Text",
                  name: "cta",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "CTA Link",
                  name: "ctaLink",
                  widget: "string",
                  required: false,
                }

      - label: "About Page"
        name: "aboutPage"
        file: "content/pages/aboutPage.json"
        fields:
          - label: "Hero Section"
            name: "heroSection"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Hero Image",
                  name: "img",
                  widget: "image",
                  hint: "image should be high resolution with an aspect ratio appropriate for the hero image",
                }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "CTA", name: "cta", widget: "string" }
              - { label: "CTA Link", name: "ctaLink", widget: "string" }
          - label: "Text Info Section"
            name: "textSection"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Main Text",
                  name: "mdMain",
                  widget: "markdown",
                  hint: "this field supports markdown, but should stick to simple things like bold, italic, etc.",
                }
              - {
                  label: "Call Out",
                  name: "mdCallout",
                  widget: "markdown",
                  hint: "this field supports markdown, but should stick to simple things like bold, italic, etc.",
                }
          - label: "Icon Section"
            name: "iconSection"
            widget: "list"
            fields:
              - { label: "heading", widget: "string", name: "heading" }
              - { label: "Details", widget: "string", name: "details" }
              - {
                  label: "icon",
                  widget: "image",
                  name: "icon",
                  hint: "SVG format",
                }
              - { label: "CTA", widget: "string", name: "cta", required: false }
              - {
                  label: "CTA Link",
                  widget: "string",
                  name: "ctaLink",
                  required: false,
                }
          - label: "Image Section"
            name: "imgSection"
            widget: "list"
            fields:
              - { label: "Image", widget: "image", name: "image" }
              - {
                  label: "Alt Text",
                  name: "altText",
                  widget: "string",
                  required: false,
                  hint: "description of the image for screen readers",
                }

          - label: "CTA Section"
            name: "ctaSection"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Details",
                  name: "mdDetails",
                  widget: "markdown",
                  hint: "this field supports markdown, but should stick to simple things like bold, italic, etc.",
                }
              - {
                  label: "CTA Text",
                  name: "cta",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "CTA Link",
                  name: "ctaLink",
                  widget: "string",
                  required: false,
                }

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "content/_settings.json"
        description: "General Site Settings"
        fields:
          - { label: "Global title", name: "siteTitle", widget: "string" }
          - {
              label: "SEO Description",
              name: "seoDescription",
              widget: "string",
            }
          - {
              label: "Pagination Size",
              name: "pageSize",
              widget: number,
              min: 1,
            }
          - label: "Navigation Links"
            name: "navbar"
            widget: "list"
            fields:
              - { label: "Display Text", name: "text", widget: "string" }
              - { label: "Link to", name: "link", widget: "string" }
